### ISSUE TITLE
CPU performance degrades when threads > 4

### ISSUE THREAD

**Issue by ealmonte32** [oracle/oracle-linux#55] opened 2022-01-31 00:05 UTC
Hi, I was doing some benchmark testing using sysbench on Oracle Linux 8 on the raspberry pi and noticed that although memory utilization and running processes out of the box in general are very good/impressive with Oracle Linux 8, that when the sysbench tool was given more than 4 threads to run, the Oracle Linux pi performed worse than a lower end pi running Rocky Linux.
For every extra 4 threads the test was given, the worse the pi running Oracle Linux performed.

I was wondering if this is a known issue?
Should this be reported somewhere else?
Below are screenshots, left is Rocky Linux and right is Oracle Linux.

![Screen Shot 2022-01-30 at 6 40 28 PM](https://user-images.githubusercontent.com/24350198/151723498-559a51d6-eef2-49a1-91d9-c6c84ad022bf.png)

![Screen Shot 2022-01-30 at 6 41 48 PM](https://user-images.githubusercontent.com/24350198/151723499-9dc6aa31-4dd8-44d3-9e33-b45e07a3d6de.png)

![Screen Shot 2022-01-30 at 6 43 19 PM](https://user-images.githubusercontent.com/24350198/151723500-975f4fce-4fc6-455d-92ac-d10f1e88f7b7.png)

![Screen Shot 2022-01-30 at 6 45 12 PM](https://user-images.githubusercontent.com/24350198/151723501-6e1ff4bb-242d-40a7-9382-49d77e657d6e.png)

![Screen Shot 2022-01-30 at 6 46 28 PM](https://user-images.githubusercontent.com/24350198/151723502-0d5f4269-2efa-478d-ad4d-8a27c752a9b8.png)

**Comment by totalamateurhour** [comment] 2022-01-31 19:01
We have some folks looking into this. One thing that may be part of the root cause is that the the UEK kernel for Oracle Linux on Arm currently uses 64K page size. The Rocky (Red Hat Compatible) kernel is likely using 4K page size.

**Comment by totalamateurhour** [comment] 2022-02-01 18:09
Couple follow up comments:

From one of our developers:

> I ran few tests with both the OS.   higher latency on oracle linux is due to  low available memory on Pi3. Sysbench needs more memory than available on RPi3 running with OL8 . As a reason it starts using swap space which causes higher latency to show up in the test.  This is not the case with Rocky linux because it's 4k pagesize  kernel. 

> I would not consider it a valid test configuration as Pi3 is not ideal for memory intensive test. Even the Rocky kernel was on the edge of using swap space with sysbench. 

Further, the Pi3 has 1GB of RAM correct?   In general, OL is aimed at larger systems and isn't necessarily tuned for hardware with such little memory.  However, disabling the services that use up the most memory might get Sysbench running at parity with your other platform.

For example:

```
sudo systemctl disable firewalld
sudo systemctl disable tuned
```

**Comment by ealmonte32** [comment] 2022-02-02 06:13
@totalamateurhour 

Sorry I guess was not specific enough about sysbench test, let me clarify:
Yes both systems have 1GB of ram, the swap partition is completely off because I disable swap for testing other stuff since it wears down the SD card, I let OOM just kill the processes whenever I am doing anything that takes up all the memory...
Those services are not running on the OL8, I have not enabled them. Ironically they both are enabled on the Rocky linux system.

The tests were CPU performance tests, not memory, thus during the tests the memory consumption had no effect on the outcome of the results.

As you can see from the screenshot taken during the CPU tests, the memory does not increase much at all and there is plenty of it free.

I tried to see if making changes to the sysctl.conf for kernel.threads-max and other parameters to have similar settings as the other OS made any difference, but it didn't.


Mem before test..
![Screen Shot 2022-02-01 at 10 53 15 PM](https://user-images.githubusercontent.com/24350198/152090949-e7521bcf-a289-4606-a147-2d0d911e59e6.png)

Mem during test..
![Screen Shot 2022-02-01 at 11 00 44 PM](https://user-images.githubusercontent.com/24350198/152091178-4e299505-c5c9-4ff6-abb0-00c194af96f5.png)

**Comment by totalamateurhour** [comment] 2022-02-04 16:08
Someone on our side is investigating this on a Pi3

**Comment by totalamateurhour** [comment] 2022-02-08 16:28
@ealmonte32 

We have replicated the issue and found that Oracle Linux is currently missing the Raspberry Pi specific [cpufreq](https://linux.die.net/man/1/cpufreq-set) module that regulates clock speed, and as a result your OL tests run with a CPU clock that is stuck at 600 MHz.  We are working on a kernel update that includes this module and will dynamically scale the clock speed according to the cpufreq governor selected ("performance", by default).   In the meantime, as a workaround you can force the clock to run at its maximum safe speed by adding the following to `/boot/efi/config.txt`:

```
arm_freq=1200
arm_freq_min=1200
```

Note that the RPi3 can (and will, in our case) overheat and shut down if you use values higher than 1200.  Please refer to the [official config.txt](https://www.raspberrypi.com/documentation/computers/config_txt.html) documentation for details.

Thanks for reporting the problem and providing the diagnostic information.

**Comment by totalamateurhour** [comment] 2022-02-15 17:27
Closing this issue for now.

**Closed by totalamateurhour** 2022-02-15 17:27 UTC

**Comment by ealmonte32** [comment] 2022-02-16 03:47
@totalamateurhour 

Thank you for looking into it and finding the culprit.
I can confirm that manually setting the cpu to 1200 (1400 is cpu default) does fix the issue.

**Comment by totalamateurhour** [comment] 2022-04-01 16:06
FYI, `5.4.17-2136.305.5.4.el8uek.aarch64` has cpufreq built in.
