### ISSUE TITLE
JQ behavior differs from RHEL-8

### ISSUE THREAD

**Issue by lpankaz** [oracle/oracle-linux#123] opened 2024-01-24 18:58 UTC
Hello, 
Not sure if this is issue, or this is working as designed, but we noticed one big difference in jq behavior between Oracle Linux 8 and RHEL 8. Up to now, we were using RHEL 8, and we decided to evaluate Oracle Linux, and transition isn't smooth. In our code, we are assuming, that performing jq command on empty string will result with exit_code=0, whereas in OL8, it returns 4. 

Simplest example: 
[rhel-8]# echo "" | jq -e
[rhel-8]# echo $?
0
 
[ol-8]# echo "" | jq -e
[ol-8]# echo $?
4

What happend? 
[ol-8]# echo "" | jq -e
[ol-8]# echo $?
4

What would we expect to happen? 
[ol-8]# echo "" | jq -e
[ol-8]# echo $?
0

**Comment by YoderExMachina** [comment] 2024-01-24 19:07
Thanks for identifying this issue.  I will open an internal ticket to have it looked at.

**Comment by YoderExMachina** [comment] 2024-01-24 19:20
I can't duplicate this.  What version of jq are you running?

$ echo ""|jq -e;echo $?
0
$ rpm -q jq
jq-1.6-6.el8.x86_64

**Comment by lpankaz** [comment] 2024-01-24 19:27
Rhel: jq-1.6-7.el8.x86_64
OL: jq-1.6-7.0.1.el8.x86_64 (the newest?)

**Comment by YoderExMachina** [comment] 2024-01-24 19:36
Got it now!

**Comment by scoter-oracle** [comment] 2024-01-24 19:49
It seems that the issue can be reproduced with "jq-1.6-7.0.1.el8.x86_64" but not with "jq-1.6-7.el8.x86_64".
Those examples are all executed on Oracle Linux 8:

[root@localhost ~]# rpm -qa |grep jq
jq-1.6-7.el8.x86_64
[root@localhost ~]# echo ""|jq -e;echo $?
0

[root@localhost ~]# rpm -qa |grep jq
jq-1.6-7.0.1.el8.x86_64
[root@localhost ~]# echo ""|jq -e;echo $?
4

**Comment by scoter-oracle** [comment] 2024-01-24 19:53
It seems that the issue is due to the "jq -e" output.
With 1.6.7, the same specifies the "jq" release on the first line:

[root@localhost ~]# jq -e
jq - commandline JSON processor [version 1.6]

with 1.6.7.0.1, the release is not showed on the first line:

[root@localhost ~]# jq -e
jq - commandline JSON processor [version -]

**Comment by scoter-oracle** [comment] 2024-01-24 20:05
@lpankaz this is clearly a bug. we already opened an internal bug to get the same fixed.
Thanks for reporting.

**Comment by YoderExMachina** [comment] 2024-02-12 15:41
This is fixed in version JQ-1.6-7.0.3.EL8_9, which should be released shortly.

**Closed by YoderExMachina** 2024-02-12 15:41 UTC
